### ISSUE TITLE
on-add script no more working. 

### ISSUE THREAD

**Issue by fplourde** [fplourde/Taskwarrior-habitica-hooks#4]
Error : 
> $ task add Appeler le médecin pour prendre rendez-vous
> Traceback (most recent call last):
>   File "/home/fplourde/.task/hooks/on-add.habitrpg.01.py", line 41, in <module>
>     main()
>   File "/home/fplourde/.task/hooks/on-add.habitrpg.01.py", line 20, in main
>     id = pushTask(jsonTask)
>   File "/home/fplourde/.task/hooks/on-add.habitrpg.01.py", line 39, in pushTask
>     return jsonHabiticaTask["id"]
> KeyError: 'id'

**Comment by fplourde** [comment]
Script updated tp use v2 API
